#ifndef _MCU_32U4_
#define _MCU_32U4_

#include "types.h"

#define INTR0 __vector_1()
#define USB_GEN __vector_10()
#define USB_COM __vector_11()
#define TIMER1_CAPT __vector_16()
#define TIMER1_COMPA __vector_17()
#define TIMER1_OVF __vector_20()
#define TIMER0_COMPA __vector_21()
#define TIMER0_COMPB __vector_22()
#define TIMER0_OVF __vector_23()
#define USART1_RX __vector_25()

#define zei()  __asm__ __volatile__ ("sei" ::: "memory")
#define zli()  __asm__ __volatile__ ("cli" ::: "memory")

static constexpr uint8_t
    portb_base = 0x23,
        pinb = portb_base,
            pinb0 = 0, pinb1 = 1, pinb2 = 2, pinb3 = 3,
            pinb4 = 4, pinb5 = 5, pinb6 = 6, pinb7 = 7,
        ddrb = portb_base + 1,
            ddb0 = 0, ddb1 = 1, ddb2 = 2, ddb3 = 3, ddb4 = 4, ddb5 = 5, ddb6 = 6, ddb7 = 7,
        portb = portb_base + 2,
            portb0 = 0, portb1 = 1, portb2 = 2, portb3 = 3,
            portb4 = 4, portb5 = 5, portb6 = 6, portb7 = 7,
            pb0 = 0, pb1 = 1, pb2 = 2, pb3 = 3, pb4 = 4, pb5 = 5, pb6 = 6, pb7 = 7,
    portc_base = 0x26,
        pinc = portc_base,
            pinc6 = 6, pinc7 = 7,
        ddrc = portc_base + 1,
            ddc6 = 6, ddc7 = 7,
        portc = portc_base + 2,
            portc6 = 6, portc7 = 7,
            pc6 = 6, pc7 = 7,
    portd_base = 0x29,
        pind = portd_base,
        ddrd = portd_base + 1,
        portd = portd_base + 2,
            portd0 = 0, portd1 = 1, portd2 = 2, portd3 = 3,
            portd4 = 4, portd5 = 5, portd6 = 6, portd7 = 7,
            pd0 = 0, pd1 = 1, pd2 = 2, pd3 = 3, pd4 = 4, pd5 = 5, pd6 = 6, pd7 = 7,
    porte_base = 0x2c,
        pine = porte_base,
        ddre = porte_base + 1,
        porte = porte_base + 2,
            porte2 = 2, porte6 = 6,
            pe2 = 2, pe6 = 6,
    portf_base = 0x2f,
        pinf = portf_base,
        ddrf = portf_base + 1,
        portf = portf_base + 2,
            portf0 = 0, portf1 = 1, portf4 = 4, portf5 = 5, portf6 = 6, portf7 = 7,
            pf0 = 0, pf1 = 1, pf4 = 4, pf5 = 5, pf6 = 6, pf7 = 7,
    tifr0 = 0x35, tov0 = 0, ocf0a = 1, ocf0b = 2,
    tifr1 = 0x36, tov1 = 0, ocf1a = 1, ocf1b = 2, ocf1c = 3, icf1 = 5,
    tifr3 = 0x38,
    tifr4 = 0x39,
    tifr5 = 0x3a,
    pcifr = 0x3b,
    eifr = 0x3c,
    eimsk = 0x3d, int0 = 0, int1 = 1, int2 = 2, int3 = 3, int4 = 4, int5 = 5, int6 = 6, int7 = 7,
    gpior0 = 0x3e,
    eecr = 0x3f,
    eedr = 0x40,
    eear = 0x41, eearl = 0x41, eearh = 0x42,
    tccr0a = 0x44, wgm00 = 0, wgm01 = 1, com0b0 = 4, com0b1 = 5, com0a0 = 6, com0a1 = 7,
    tccr0b = 0x45, cs00 = 0, cs01 = 1, cs02 = 2, wgm02 = 3, foc0b = 6, foc0a = 7,
    tcnt0 = 0x46,
    ocr0a = 0x47,
    ocr0b = 0x48,
    pllcsr = 0x49, plock = 0, plle = 1, pindiv = 4,
    gpior1 = 0x4a,
    gpior2 = 0x4b,
    spcr = 0x4c, spr0 = 0, spr1 = 1, cpha = 2, cpol = 3, mstr = 4, dord = 5, spe = 6, spie = 7,
    spsr = 0x4d, spi2x = 0, wcol = 6, spif = 7,
    spdr = 0x4e,
    acsr = 0x50, acd = 7, acbg = 6, aco = 5, aci = 4, acie = 3, acic = 2, acis1 = 1, acis0 = 0,
    mondr = 0x51, ocdr = 0x51, idrd = 7, ocdr7 = 7, ocdr6 = 6, ocdr5 = 5, ocdr4 = 4,
        ocdr3 = 3, ocdr2 = 2, ocdr1 = 1, ocdr0 = 0,
    pllfrq = 0x52,
        pdiv0 = 0, pdiv1 = 1, pdiv2 = 2, pdiv3 = 3,
        plltm0 = 4, plltm1 = 5, pllusb = 6, pinmux = 7,
    mcusr = 0x54,
    mcucr = 0x55,
    eicra = 0x69, isc00 = 0, isc01 = 1, isc10 = 2, isc11 = 3, isc20 = 4, isc30 = 6, isc31 = 7,
    timsk0 = 0x6e, toie0 = 0, ocie0a = 1, ocie0b = 2,
    timsk1 = 0x6f, toie1 = 0, ocie1a = 1, ocie1b = 2, ocie1c = 3, icie1 = 5,
    timsk3 = 0x71, toie3 = 0, ocie3a = 1, ocie3b = 2, ocie3c = 3, icie3 = 5,
    timsk4 = 0x72, toie4 = 2, ocie4b = 5, ocie4a = 6, ocie4d = 7,
    adcl = 0x78,
    adch = 0x79,
    adcsra = 0x7a,
        adps0 = 0, adps1 = 1, adps2 = 2, adie = 3, adif = 4, adate = 5, adsc = 6, aden = 7,
    adcsrb = 0x7b, adts0 = 0, adts1 = 1, adts2 = 2, adts3 = 3, mux5 = 5, acme = 6, adhsm = 7,
    admux = 0x7c,
        mux0 = 0, mux1 = 1, mux2 = 2, mux3 = 3, mux4 = 4, adlar = 5, refs0 = 6, refs1 = 7,
    didr2 = 0x7d,
    didr0 = 0x7e,
    didr1 = 0x7f, ain0d = 0, ain1d = 1,
    tccr1a = 0x80,
        wgm10 = 0, wgm11 = 1, com1c0 = 2, com1c1 = 3,
        com1b0 = 4, com1b1 = 5, com1a0 = 6, com1a1 = 7,
    tccr1b = 0x81, cs10 = 0, cs11 = 1, cs12 = 2, wgm12 = 3, wgm13 = 4, ines1 = 6, icnc1 = 7,
    tccr1c = 0x82, foc1c = 5, foc1b = 6, foc1a = 7,
    tcnt1 = 0x84,
    tcnt1l = 0x84,
    tcnt1h = 0x85,
    icr1 = 0x86,
    icr1l = 0x86,
    icr1h = 0x87,
    ocr1a = 0x88,
    ocr1al = 0x88,
    ocr1ah = 0x89,
    ocr1b = 0x8a,
    ocr1bl = 0x8a,
    ocr1bh = 0x8b,
    ocr1c = 0x8c,
    ocr1cl = 0x8c,
    ocr1ch = 0x8d,
    tccr3a = 0x90,
        wgm30 = 0, wgm31 = 1, com3c0 = 2, com3c1 = 3,
        com3b0 = 4, com3b1 = 5, com3a0 = 6, com3a1 = 7,
    tccr3b = 0x91, cs30 = 0, cs31 = 1, cs32 = 2, wgm32 = 3, wgm33 = 4, ices3 = 6, icnc3 = 7,
    tccr3c = 0x92,
    tcnt3 = 0x94,
    tcnt3l = 0x94,
    tcnt3h = 0x95,
    icr3l = 0x96,
    icr3h = 0x97,
    ocr3a = 0x98,
    ocr3al = 0x98,
    ocr3ah = 0x99,
    ocr3b = 0x9a,
    ocr3bl = 0x9a,
    ocr3bh = 0x9b,
    twbr = 0xb8,
    twsr = 0xb9,
    twar = 0xba,
    ucsr1a = 0xc8,
        mpcm1 = 0, u2x1 = 1, upe1 = 2, dor1 = 3,
        fe1 = 4, udre1 = 5, txc1 = 6, rxc1 = 7,
    ucsr1b = 0xc9,
        txb81 = 0, rxb81 = 1, ucsz12 = 2, txen1 = 3,
        rxen1 = 4, udrie1 = 5, txcie1 = 6, rxcie1 = 7,
    ucsr1c = 0xca,
        ucpol1 = 0, ucsz10 = 1, ucsz11 = 2, usbs1 = 3,
        upm10 = 4, upm11 = 5, umsel10 = 6, umsel11 = 7,
    ucsr1d = 0xcb, rtsen = 0, ctsen = 1,
    ubrr1 = 0xcc, ubrr1l = 0xcc, ubrr1h = 0xcd,
    udr1 = 0xce,
    uhwcon = 0xd7, uvrege = 0,
    usbcon = 0xd8, vbuste = 0, otgpade = 4, frzclk = 5, usbe = 7,
    usbsta = 0xd9, vbus = 0, speed = 3,
    usbint = 0xda, vbusti = 0,
    udcon = 0xe0, detach = 0, rmwkup = 1, lsm = 2, rstcpu = 3,
    udint = 0xe1, suspi = 0, sofi = 2, eorsti = 3, wakeupi = 4, eorsmi = 5, uprsmi = 6,
    udien = 0xe2, suspe = 0, sofe = 2, eorste = 3, wakeupe = 4, eorshe = 5, uprsme = 6,
    udaddr = 0xe3,
        adden = 7,
    udfnum = 0xe4, udfnuml = 0xe4, udfnumh = 0xe5,
    udmfn = 0xe6,
    ueintx = 0xe8,
        txini = 0, stalledi = 1, rxouti = 2, rxstpi = 3,
        nakouti = 4, rwal = 5, nakini = 6, fifocon = 7,
    uenum = 0xe9,
    uerst = 0xea,
    ueconx = 0xeb, epen = 0, rstdt = 3, stallrqc = 4, stallrq = 5,
    uecfg0x = 0xec, epdir = 0, eptype0 = 6, eptype1 = 7,
    uecfg1x = 0xed, alloc = 1, epbk0 = 2, epbk1 = 3, epsize0 = 4, epsize1 = 5, epsize2 = 6,
    ueienx = 0xf0,
        txine = 0, stallede = 1, rxoute = 2, rxstpe = 3, nakoute = 4, nakine = 6, flerre = 7,
    uedatx = 0xf1,
    uebcx = 0xf2,
    uebclx = 0xf2,
    uebchx = 0xf3,
    ueint = 0xf4,

    ocr0a_base = portb_base,
    ocr0a_in = ocr0a_base + 0,
    ocr0a_ddr = ocr0a_base + 1,
    ocr0a_port = ocr0a_base + 2,
    ocr0a_bit = pb7,
    ocr0b_base = portd_base,
    ocr0b_ddr = ocr0b_base + 1,
    ocr0b_bit = pd0,
    ocr1a_base = portb_base,
    ocr1a_in = ocr1a_base + 0,
    ocr1a_ddr = ocr1a_base + 1,
    ocr1a_port = ocr1a_base + 2,
    ocr1a_bit = pb5,
    ocr1b_base = portb_base,
    ocr1b_in = ocr1b_base + 0,
    ocr1b_ddr = ocr1b_base + 1,
    ocr1b_port = ocr1b_base + 2,
    ocr1b_bit = pb6,
    
    int0_port_base = portd_base,
    int0_in = int0_port_base + 0,
    int0_ddr = int0_port_base + 1,
    int0_port = int0_port_base + 2,
    int0_bit = pd0,

    ss_port_base = portb_base,
    ss_in = ss_port_base + 0,
    ss_ddr = ss_port_base + 1,
    ss_port = ss_port_base + 2,
    ss_bit = pb0,
    sck_port_base = portb_base,
    sck_in = sck_port_base + 0,
    sck_ddr = sck_port_base + 1,
    sck_port = sck_port_base + 2,
    sck_bit = pb1,
    mosi_port_base = portb_base,
    mosi_in = mosi_port_base + 0,
    mosi_ddr = mosi_port_base + 1,
    mosi_port = mosi_port_base + 2,
    mosi_bit = pb2,
    miso_port_base = portb_base,
    miso_in = miso_port_base + 0,
    miso_ddr = miso_port_base + 1,
    miso_port = miso_port_base + 2,
    miso_bit = pb3;

static volatile uint8_t
    * const p_pinb = (volatile uint8_t * const)pinb,
    * const p_ddrb = (volatile uint8_t * const)ddrb,
    * const p_portb = (volatile uint8_t * const)portb,
    * const p_pinc = (volatile uint8_t * const)pinc,
    * const p_ddrc = (volatile uint8_t * const)ddrc,
    * const p_portc = (volatile uint8_t * const)portc,
    * const p_ddrd = (volatile uint8_t * const)ddrd,
    * const p_portd = (volatile uint8_t * const)portd,
    * const p_pinf = (volatile uint8_t * const)pinf,
    * const p_ddrf = (volatile uint8_t * const)ddrf,
    * const p_portf = (volatile uint8_t * const)portf,
    * const p_tifr0 = (volatile uint8_t * const)tifr0,
    * const p_tifr1 = (volatile uint8_t * const)tifr1,
    * const p_tifr3 = (volatile uint8_t * const)tifr3,
    * const p_tifr4 = (volatile uint8_t * const)tifr4,
    * const p_tifr5 = (volatile uint8_t * const)tifr5,
    * const p_eimsk = (volatile uint8_t * const)eimsk,
    * const p_tccr0a = (volatile uint8_t * const)tccr0a,
    * const p_tccr0b = (volatile uint8_t * const)tccr0b,
    * const p_tcnt0 = (volatile uint8_t * const)tcnt0,
    * const p_ocr0a = (volatile uint8_t * const)ocr0a,
    * const p_ocr0b = (volatile uint8_t * const)ocr0b,
    * const p_pllcsr = (volatile uint8_t * const)pllcsr,
    * const p_gpior1 = (volatile uint8_t * const)gpior1,
    * const p_gpior2 = (volatile uint8_t * const)gpior2,
    * const p_spcr = (volatile uint8_t * const)spcr,
    * const p_spsr = (volatile uint8_t * const)spsr,
    * const p_spdr = (volatile uint8_t * const)spdr,
    * const p_pllfrq = (volatile uint8_t * const)pllfrq,
    * const p_eicra = (volatile uint8_t * const)eicra,
    * const p_timsk0 = (volatile uint8_t * const)timsk0,
    * const p_timsk1 = (volatile uint8_t * const)timsk1,
    * const p_timsk3 = (volatile uint8_t * const)timsk3,
    * const p_timsk4 = (volatile uint8_t * const)timsk4,
    * const p_adcl = (volatile uint8_t * const)adcl,
    * const p_adch = (volatile uint8_t * const)adch,
    * const p_adcsra = (volatile uint8_t * const)adcsra,
    * const p_adcsrb = (volatile uint8_t * const)adcsrb,
    * const p_admux = (volatile uint8_t * const)admux,
    * const p_didr0 = (volatile uint8_t * const)didr0,
    * const p_tccr1a = (volatile uint8_t * const)tccr1a,
    * const p_tccr1b = (volatile uint8_t * const)tccr1b,
    * const p_tccr1c = (volatile uint8_t * const)tccr1c,
    * const p_tccr3a = (volatile uint8_t * const)tccr3a,
    * const p_tccr3b = (volatile uint8_t * const)tccr3b,
    * const p_tccr3c = (volatile uint8_t * const)tccr3c,
    * const p_ocr3a = (volatile uint8_t * const)ocr3a,
    * const p_ocr3b = (volatile uint8_t * const)ocr3b,
    * const p_twbr = (volatile uint8_t * const)twbr,
    * const p_twsr = (volatile uint8_t * const)twsr,
    * const p_twar = (volatile uint8_t * const)twar,
    * const p_ucsr1a = (volatile uint8_t * const)ucsr1a,
    * const p_ucsr1b = (volatile uint8_t * const)ucsr1b,
    * const p_ubrr1l = (volatile uint8_t * const)ubrr1l,
    * const p_ubrr1h = (volatile uint8_t * const)ubrr1h,
    * const p_udr1 = (volatile uint8_t * const)udr1,
    * const p_uhwcon = (volatile uint8_t * const)uhwcon,
    * const p_usbcon = (volatile uint8_t * const)usbcon,
    * const p_usbsta = (volatile uint8_t * const)usbsta,
    * const p_usbint = (volatile uint8_t * const)usbint,
    * const p_udcon = (volatile uint8_t * const)udcon,
    * const p_udint = (volatile uint8_t * const)udint,
    * const p_udien = (volatile uint8_t * const)udien,
    * const p_udaddr = (volatile uint8_t * const)udaddr,
    * const p_udfnuml = (volatile uint8_t * const)udfnuml,
    * const p_ueintx = (volatile uint8_t * const)ueintx,
    * const p_uenum = (volatile uint8_t * const)uenum,
    * const p_uerst = (volatile uint8_t * const)uerst,
    * const p_ueconx = (volatile uint8_t * const)ueconx,
    * const p_uecfg0x = (volatile uint8_t * const)uecfg0x,
    * const p_uecfg1x = (volatile uint8_t * const)uecfg1x,
    * const p_ueienx = (volatile uint8_t * const)ueienx,
    * const p_uedatx = (volatile uint8_t * const)uedatx,
    * const p_uebclx = (volatile uint8_t * const)uebclx,
    * const p_uebchx = (volatile uint8_t * const)uebchx,
    * const p_ueint = (volatile uint8_t * const)ueint,

    * const p_ocr0a_ddr = (volatile uint8_t * const)ocr0a_ddr,
    * const p_ocr0b_ddr = (volatile uint8_t * const)ocr0b_ddr,
    * const p_ocr1a_in = (volatile uint8_t * const)ocr1a_in,
    * const p_ocr1a_ddr = (volatile uint8_t * const)ocr1a_ddr,
    * const p_ocr1a_port = (volatile uint8_t * const)ocr1a_port,
    * const p_ocr1b_in = (volatile uint8_t * const)ocr1b_in,
    * const p_ocr1b_ddr = (volatile uint8_t * const)ocr1b_ddr,
    * const p_ocr1b_port = (volatile uint8_t * const)ocr1b_port,
    
    * const p_int0_ddr = (volatile uint8_t * const)int0_ddr,
    * const p_int0_port = (volatile uint8_t * const)int0_port,
    
    * const p_ss_ddr = (volatile uint8_t * const)ss_ddr,
    * const p_ss_port = (volatile uint8_t * const)ss_port,
    * const p_sck_ddr = (volatile uint8_t * const)sck_ddr,
    * const p_sck_port = (volatile uint8_t * const)sck_port,
    * const p_mosi_ddr = (volatile uint8_t * const)mosi_ddr,
    * const p_mosi_port = (volatile uint8_t * const)mosi_port,
    * const p_miso_ddr = (volatile uint8_t * const)miso_ddr,
    * const p_miso_port = (volatile uint8_t * const)miso_port;

static volatile uint16_t
    * const p_icr1 = (volatile uint16_t * const)icr1,
    * const p_ocr1a = (volatile uint16_t * const)ocr1a,
    * const p_ocr1b = (volatile uint16_t * const)ocr1b,
    * const p_ocr1c = (volatile uint16_t * const)ocr1c,
    * const p_ubrr1 = (volatile uint16_t * const)ubrr1,
    * const p_udfnum = (volatile uint16_t * const)udfnum;

#endif



